### ISSUE TITLE
issues content and style image 

### ISSUE THREAD

**Issue by oltip** [sdhnshu/artistic-style-transfer-on-floydhub#1]
Hi,  thank you for this example. However, trying to replicate it, the jupyter notebook in floyd does not upload the content and style image. So, it does not find the path ".content.jpg')   

Do you have any idea, why is that?

**Comment by sdhnshu** [comment]
content.jpg should be located in the same folder as the jupyter notebook while uploading and the path should be './content.jpg'

**Comment by oltip** [comment]
Ok. I will try to figure out what's the issue. Many thanks anyway !!!
