### ISSUE TITLE
Data not found (jq4ZXUCSVer4t65rWeyieG)

### ISSUE THREAD

**Issue by vaibhavahuja** [sdhnshu/artistic-style-transfer-on-floydhub#2]
on using the command 
`floyd run --mode jupyter --gpu --env tensorflow-1.0 --data jq4ZXUCSVer4t65rWeyieG`

it gives an error saying the data id is incorrect. Could you please see to it? And i further tried using some other VGG19 data available on their website but unable to use it. Help please?

**Comment by sdhnshu** [comment]
The structure of FloydHub was a little different when I wrote this. You can check [this](https://docs.floydhub.com/guides/data/mounting_data/#example-2) example to find out how to mount. And the [this](https://www.floydhub.com/floydhub/datasets/imagenet-vgg-verydeep-19) vgg19 dataset (in .mat format)
